version: "3"
services:
  nginx:
    container_name: nginx1
    image: nginx:latest
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php-fpm:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html

  mysql-fpm:
    container_name: mysql
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: "rikkeisoft1"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - 3308:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  adminer:
    container_name: admin
    image: adminer
    restart: always
    ports:
      - 8083:8080
volumes:
  mysqldata: {}
